# Generated by Django 4.1.4 on 2023-01-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_biography_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='text',
            new_name='name',
        ),
    ]
